services:
  mongodb:
    image: mongo:7
    container_name: track_learn_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: track_learn_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - track_learn_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: track_learn_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - track_learn_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: track_learn_frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - track_learn_network

volumes:
  mongodb_data:

networks:
  track_learn_network:
    driver: bridge
